server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health-tracker-for-fridge?serverTimeZone=GMT%2b8
    username: root
    password: "00000000"

mybatis:
  mapper-locations: classpath:mapper/*.xml #scan all mybatis .xml file
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  #mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


